version: "3.3"
services:
  front:
    image: nginx
    network_mode: host
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./site
        target: /usr/share/nginx/front/
